version: "3.7"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    volumes:
        - postgres-storage:/var/lib/postgresql/data
        - ./configurations/sql/:/docker-entrypoint-initdb.d/
  keycloak:
    image: jboss/keycloak
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_ADDR: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: keycloak

volumes:
  postgres-storage:

